### ISSUE TITLE
This expression is not callable.   

### ISSUE THREAD

**Issue by saito-kosuke** [boywithkeyboard-archive/is-disposable#2] opened 2023-06-22 03:07 UTC
The error has occurred to me.

This expression is not callable.
  Type 'typeof import("/Users/test/transcope/node_modules/is-disposable/index")' has no call signatures.ts(2349)

**Comment by JuroOravec** [comment] 2023-06-22 07:33
Got same just now. Looks like the issue is that the function is defined as a **default** export, but the type declaration defines it as a **named** export.

I've just tested in my workspace (VSCode). Looks like it should be fixed by changing [this line in index.d.ts](https://github.com/boywithkeyboard/is-disposable/blob/4e52dec5d9d547b1ea42119792700b9e0be0899a/index.d.ts#L1). (cc @boywithkeyboard)

```ts
export declare function isDisposable(email:string,{remote}?:{remote?:boolean|undefined},):Promise<boolean>
```
to this

```ts
export default function isDisposable(email:string,{remote}?:{remote?:boolean|undefined},):Promise<boolean>
```

(`declare` was changed to `default`)

**Comment by saito-kosuke** [comment] 2023-06-22 07:56
@JuroOravec, I'm all for it. Could you create a PR for us?

**Comment by boywithkeyboard** [comment] 2023-06-22 08:06
I'll fix this issue in ~1h.

**Closed as completed** 2023-06-22 09:00 UTC

**Comment by JuroOravec** [comment] 2023-06-22 12:07
Wow, thanks for fixing it so fast!

**Comment by boywithkeyboard** [comment] 2023-06-22 12:12
@JuroOravec you're welcome! 🤗

**Comment by saito-kosuke** [comment] 2023-06-23 01:19
@boywithkeyboard It works well in my environment as well. I greatly appreciate your fix.
